# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml
github: https://github.com/superalsrk
version: 0.0.0
# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- about_me
- category
- tag
- tagcloud
- recent_posts
- links

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
baidu_tongji: 023671609eb87ab0b372df8f19b59d48
favicon: /favicon.ico

twitter: superalsrk
google_plus:
fb_admins:
fb_app_id:

# Toc
toc:
  article: false   ## show contents in article.
  aside: false     ## show contents in aside.
# Scroll to top
go_top: true

# baidu share
baidushare: true

# blogroll

links:
- name: Gates of Janus
  link: http://wilbeibi.com/
- name: Uranux小彬彬
  link: http://uranux.com/
- name: 天羽ちよこ
  link: http://choco.properties/
- name: Tesop彬哥
  link: http://blog.tesop.cn/

# about me
about_me:
  title: ABOUT ME
  gravatar: superalsrk@gmail.com
  avatar: /images/ua.jpg
  texts:
  - Hi,I'm superalsrk.

# display updated
display_updated: true

# 不蒜子
busuanzi: false


gitalk:
  enable: true ## If you want to use Gitment comment system please set the value to true.
  owner:  superalsrk ## Your GitHub ID, e.g. username
  repo: superalsrk.github.com ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
  client_id: 4bc95ec3ac354b32457f ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: f94bbda0540f91292aed00012e637addce3f2b0e  ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
  admin: superalsrk ## Github repo owner and collaborators, only these guys can initialize github issues.